import { createFileRoute } from "@tanstack/react-router";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { createMondayItem } from "@/lib/monday.server";
import type { ForgeResult } from "@/lib/agents.server";

const AUTH_ERROR = "Authentication required. Please sign in.";
const MAX_DESCRIPTION_CHARS = 9000; // Monday long-text column safe size

/**
 * Build a human-readable implementation guide from a Forge result.
 * Used both as the Monday.com item description and the "Copy Full
 * Implementation Guide" output on the client.
 */
function buildImplementationGuide(forge: ForgeResult, title: string): string {
  const lines: string[] = [];
  const h = (s: string) => lines.push("", `## ${s}`, "");
  const p = (s: string) => lines.push(s);

  p(`# ${title}`);
  p("");
  p("_Generated by LUNAVX Forge — ready-to-deploy automation package._");

  if (forge.trigger) {
    h("Trigger");
    p(forge.trigger);
  }

  if (forge.estimatedRoi) {
    h("Estimated Revenue Impact");
    p(forge.estimatedRoi);
  }
  if (forge.roiProjection) {
    const r = forge.roiProjection;
    const rows = [
      r.bookedJobsLiftPct && `- Booked jobs lift: ${r.bookedJobsLiftPct}`,
      r.noShowReductionPct && `- No-show reduction: ${r.noShowReductionPct}`,
      r.reviewVelocityMultiplier &&
        `- Review velocity: ${r.reviewVelocityMultiplier}`,
      r.monthlyRevenueLiftUsd &&
        `- Monthly revenue lift: ${r.monthlyRevenueLiftUsd}`,
      r.paybackPeriod && `- Payback period: ${r.paybackPeriod}`,
    ].filter(Boolean);
    if (rows.length) lines.push(...(rows as string[]));
  }

  if (forge.steps?.length) {
    h("Automation Flow");
    forge.steps.forEach((s, i) =>
      p(`${i + 1}. **${s.action}** — ${s.details}`),
    );
  }

  if (forge.integrations?.length) {
    h("Integrations");
    p(forge.integrations.join(", "));
  }

  if (forge.integrationGuide?.length) {
    h("Integration Setup");
    forge.integrationGuide.forEach((g) => {
      p(`### ${g.provider}${g.purpose ? ` — ${g.purpose}` : ""}`);
      g.setupSteps?.forEach((s, i) => p(`${i + 1}. ${s}`));
      if (g.envVars?.length) p(`Env vars: ${g.envVars.join(", ")}`);
      p("");
    });
  }

  if (forge.emailTemplates?.length) {
    h("Email Templates");
    forge.emailTemplates.forEach((t) => {
      p(`### ${t.name}`);
      p(`Subject: ${t.subject}`);
      p("");
      p(t.body);
      p("");
    });
  }

  if (forge.smsTemplates?.length) {
    h("SMS Templates");
    forge.smsTemplates.forEach((t) => p(`- **${t.name}** — ${t.body}`));
  }

  if (forge.bookingSetup) {
    h("Booking Setup");
    const b = forge.bookingSetup;
    if (b.platform) p(`- Platform: ${b.platform}`);
    if (b.eventName) p(`- Event: ${b.eventName}`);
    if (b.duration) p(`- Duration: ${b.duration}`);
    if (b.buffer) p(`- Buffer: ${b.buffer}`);
    if (b.intakeQuestions?.length) {
      p(`- Intake questions:`);
      b.intakeQuestions.forEach((q) => p(`  - ${q}`));
    }
    if (b.confirmation) p(`- Confirmation: ${b.confirmation}`);
    if (b.reminders?.length) p(`- Reminders: ${b.reminders.join(" • ")}`);
  }

  if (forge.reviewRequest) {
    h("Review Request");
    const r = forge.reviewRequest;
    if (r.platform) p(`- Platform: ${r.platform}`);
    if (r.timing) p(`- Timing: ${r.timing}`);
    if (r.linkFormat) p(`- Link: ${r.linkFormat}`);
    if (r.message) p(`- Message: ${r.message}`);
  }

  if (forge.kpis?.length) {
    h("KPIs");
    forge.kpis.forEach((k) => p(`- ${k}`));
  }

  if (forge.nextActions?.length) {
    h("Next Actions");
    forge.nextActions.forEach((a, i) => {
      const meta = [a.owner, a.eta].filter(Boolean).join(" • ");
      p(`${i + 1}. **${a.title}**${meta ? ` _(${meta})_` : ""}`);
      if (a.why) p(`   ${a.why}`);
    });
  }

  if (forge.snippets?.length) {
    h("Snippets");
    forge.snippets.forEach((s) => {
      p(`### ${s.title}`);
      p("```" + (s.language || "text"));
      p(s.code);
      p("```");
      p("");
    });
  }

  return lines.join("\n").trim();
}

export const Route = createFileRoute("/api/save-automation")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        try {
          // ── Auth ────────────────────────────────────────────────────────
          const authHeader = request.headers.get("authorization") || "";
          if (!authHeader.toLowerCase().startsWith("bearer ")) {
            return Response.json(
              { success: false, error: AUTH_ERROR },
              { status: 401 },
            );
          }
          const token = authHeader.slice(7).trim();
          if (!token) {
            return Response.json(
              { success: false, error: AUTH_ERROR },
              { status: 401 },
            );
          }
          const { data: userData, error: userErr } =
            await supabaseAdmin.auth.getUser(token);
          const user = userData?.user;
          if (userErr || !user) {
            return Response.json(
              { success: false, error: AUTH_ERROR },
              { status: 401 },
            );
          }

          // ── Rate limit: 20 requests per hour per user ──────────────────
          const { data: rlAllowed, error: rlErr } = await supabaseAdmin.rpc(
            "check_rate_limit",
            {
              p_user_id: user.id,
              p_route: "save-automation",
              p_max_requests: 20,
              p_window_seconds: 3600,
            },
          );
          if (rlErr) {
            console.error("[save-automation] rate limit check failed");
            return Response.json({ success: false, error: "Service temporarily unavailable" }, { status: 503 });
          }
          if (!rlAllowed) {
            return Response.json({ success: false, error: "Too many requests. Please wait a bit and try again." }, { status: 429 });
          }

          // ── Input ───────────────────────────────────────────────────────
          const body = (await request.json().catch(() => ({}))) as {
            title?: unknown;
            forge?: unknown;
          };
          const title =
            typeof body.title === "string" && body.title.trim()
              ? body.title.trim().slice(0, 200)
              : "Forge Automation Blueprint";
          const forge = body.forge as ForgeResult | undefined;
          if (!forge || typeof forge !== "object" || !Array.isArray(forge.steps)) {
            return Response.json(
              {
                success: false,
                error:
                  "Missing or invalid 'forge' payload. Run an automation workflow first.",
              },
              { status: 400 },
            );
          }

          const guide = buildImplementationGuide(forge, title);
          const truncatedGuide =
            guide.length > MAX_DESCRIPTION_CHARS
              ? `${guide.slice(0, MAX_DESCRIPTION_CHARS)}\n\n…(truncated)`
              : guide;

          // ── Save to Monday.com as a new lead-board item ─────────────────
          const itemName = `🤖 ${title}`;
          const columnValues: Record<string, unknown> = {
            color_mm40t58z: { label: "Hot" },
            text_mm408bbv: "Forge Automation",
            text_mm40qp3y: truncatedGuide.slice(0, 1900), // short summary column
          };

          const itemId = await createMondayItem(itemName, columnValues);

          console.log(
            `[/api/save-automation] user=${user.id} saved Monday item=${itemId}`,
          );

          return Response.json({
            success: true,
            itemId,
            title: itemName,
            guideChars: guide.length,
          });
        } catch (err) {
          console.error("/api/save-automation error:", err);
          return Response.json(
            {
              success: false,
              error: err instanceof Error ? err.message : "Unknown server error",
            },
            { status: 500 },
          );
        }
      },
    },
  },
});
