/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiWorkflowRouteImport } from './routes/api/workflow'
import { Route as ApiSaveAutomationRouteImport } from './routes/api/save-automation'
import { Route as ApiGenerateWeeklyPlanRouteImport } from './routes/api/generate-weekly-plan'
import { Route as ApiGenerateContentRouteImport } from './routes/api/generate-content'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as AuthenticatedAppWorkflowsRouteImport } from './routes/_authenticated/app.workflows'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppLogsRouteImport } from './routes/_authenticated/app.logs'
import { Route as AuthenticatedAppControlRouteImport } from './routes/_authenticated/app.control'
import { Route as AuthenticatedAppChatRouteImport } from './routes/_authenticated/app.chat'
import { Route as AuthenticatedAppAgentsRouteImport } from './routes/_authenticated/app.agents'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicChatbotBusiness_idRouteImport } from './routes/api/public/chatbot/$business_id'
import { Route as ApiPublicBillingPortalRouteImport } from './routes/api/public/billing/portal'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowRoute = ApiWorkflowRouteImport.update({
  id: '/api/workflow',
  path: '/api/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveAutomationRoute = ApiSaveAutomationRouteImport.update({
  id: '/api/save-automation',
  path: '/api/save-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateWeeklyPlanRoute = ApiGenerateWeeklyPlanRouteImport.update({
  id: '/api/generate-weekly-plan',
  path: '/api/generate-weekly-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateContentRoute = ApiGenerateContentRouteImport.update({
  id: '/api/generate-content',
  path: '/api/generate-content',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppWorkflowsRoute =
  AuthenticatedAppWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLogsRoute = AuthenticatedAppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppControlRoute = AuthenticatedAppControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChatRoute = AuthenticatedAppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgentsRoute = AuthenticatedAppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicChatbotBusiness_idRoute =
  ApiPublicChatbotBusiness_idRouteImport.update({
    id: '/api/public/chatbot/$business_id',
    path: '/api/public/chatbot/$business_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBillingPortalRoute = ApiPublicBillingPortalRouteImport.update({
  id: '/api/public/billing/portal',
  path: '/api/public/billing/portal',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/generate-weekly-plan': typeof ApiGenerateWeeklyPlanRoute
  '/api/save-automation': typeof ApiSaveAutomationRoute
  '/api/workflow': typeof ApiWorkflowRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/app/agents': typeof AuthenticatedAppAgentsRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/control': typeof AuthenticatedAppControlRoute
  '/app/logs': typeof AuthenticatedAppLogsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/chatbot/$business_id': typeof ApiPublicChatbotBusiness_idRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/generate-weekly-plan': typeof ApiGenerateWeeklyPlanRoute
  '/api/save-automation': typeof ApiSaveAutomationRoute
  '/api/workflow': typeof ApiWorkflowRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/app/agents': typeof AuthenticatedAppAgentsRoute
  '/app/chat': typeof AuthenticatedAppChatRoute
  '/app/control': typeof AuthenticatedAppControlRoute
  '/app/logs': typeof AuthenticatedAppLogsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/chatbot/$business_id': typeof ApiPublicChatbotBusiness_idRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/api/generate-content': typeof ApiGenerateContentRoute
  '/api/generate-weekly-plan': typeof ApiGenerateWeeklyPlanRoute
  '/api/save-automation': typeof ApiSaveAutomationRoute
  '/api/workflow': typeof ApiWorkflowRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/_authenticated/app/agents': typeof AuthenticatedAppAgentsRoute
  '/_authenticated/app/chat': typeof AuthenticatedAppChatRoute
  '/_authenticated/app/control': typeof AuthenticatedAppControlRoute
  '/_authenticated/app/logs': typeof AuthenticatedAppLogsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/public/billing/portal': typeof ApiPublicBillingPortalRoute
  '/api/public/chatbot/$business_id': typeof ApiPublicChatbotBusiness_idRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/auth'
    | '/chat'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/app'
    | '/api/generate-content'
    | '/api/generate-weekly-plan'
    | '/api/save-automation'
    | '/api/workflow'
    | '/checkout/return'
    | '/app/agents'
    | '/app/chat'
    | '/app/control'
    | '/app/logs'
    | '/app/settings'
    | '/app/workflows'
    | '/api/public/leads'
    | '/app/'
    | '/api/public/billing/portal'
    | '/api/public/chatbot/$business_id'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/auth'
    | '/chat'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/api/generate-content'
    | '/api/generate-weekly-plan'
    | '/api/save-automation'
    | '/api/workflow'
    | '/checkout/return'
    | '/app/agents'
    | '/app/chat'
    | '/app/control'
    | '/app/logs'
    | '/app/settings'
    | '/app/workflows'
    | '/api/public/leads'
    | '/app'
    | '/api/public/billing/portal'
    | '/api/public/chatbot/$business_id'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/audit'
    | '/auth'
    | '/chat'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/_authenticated/app'
    | '/api/generate-content'
    | '/api/generate-weekly-plan'
    | '/api/save-automation'
    | '/api/workflow'
    | '/checkout/return'
    | '/_authenticated/app/agents'
    | '/_authenticated/app/chat'
    | '/_authenticated/app/control'
    | '/_authenticated/app/logs'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/workflows'
    | '/api/public/leads'
    | '/_authenticated/app/'
    | '/api/public/billing/portal'
    | '/api/public/chatbot/$business_id'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiGenerateContentRoute: typeof ApiGenerateContentRoute
  ApiGenerateWeeklyPlanRoute: typeof ApiGenerateWeeklyPlanRoute
  ApiSaveAutomationRoute: typeof ApiSaveAutomationRoute
  ApiWorkflowRoute: typeof ApiWorkflowRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
  ApiPublicBillingPortalRoute: typeof ApiPublicBillingPortalRoute
  ApiPublicChatbotBusiness_idRoute: typeof ApiPublicChatbotBusiness_idRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow': {
      id: '/api/workflow'
      path: '/api/workflow'
      fullPath: '/api/workflow'
      preLoaderRoute: typeof ApiWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-automation': {
      id: '/api/save-automation'
      path: '/api/save-automation'
      fullPath: '/api/save-automation'
      preLoaderRoute: typeof ApiSaveAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-weekly-plan': {
      id: '/api/generate-weekly-plan'
      path: '/api/generate-weekly-plan'
      fullPath: '/api/generate-weekly-plan'
      preLoaderRoute: typeof ApiGenerateWeeklyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-content': {
      id: '/api/generate-content'
      path: '/api/generate-content'
      fullPath: '/api/generate-content'
      preLoaderRoute: typeof ApiGenerateContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/workflows': {
      id: '/_authenticated/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AuthenticatedAppWorkflowsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/logs': {
      id: '/_authenticated/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AuthenticatedAppLogsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/control': {
      id: '/_authenticated/app/control'
      path: '/control'
      fullPath: '/app/control'
      preLoaderRoute: typeof AuthenticatedAppControlRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/chat': {
      id: '/_authenticated/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AuthenticatedAppChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agents': {
      id: '/_authenticated/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AuthenticatedAppAgentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chatbot/$business_id': {
      id: '/api/public/chatbot/$business_id'
      path: '/api/public/chatbot/$business_id'
      fullPath: '/api/public/chatbot/$business_id'
      preLoaderRoute: typeof ApiPublicChatbotBusiness_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/billing/portal': {
      id: '/api/public/billing/portal'
      path: '/api/public/billing/portal'
      fullPath: '/api/public/billing/portal'
      preLoaderRoute: typeof ApiPublicBillingPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgentsRoute: typeof AuthenticatedAppAgentsRoute
  AuthenticatedAppChatRoute: typeof AuthenticatedAppChatRoute
  AuthenticatedAppControlRoute: typeof AuthenticatedAppControlRoute
  AuthenticatedAppLogsRoute: typeof AuthenticatedAppLogsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppWorkflowsRoute: typeof AuthenticatedAppWorkflowsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgentsRoute: AuthenticatedAppAgentsRoute,
  AuthenticatedAppChatRoute: AuthenticatedAppChatRoute,
  AuthenticatedAppControlRoute: AuthenticatedAppControlRoute,
  AuthenticatedAppLogsRoute: AuthenticatedAppLogsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppWorkflowsRoute: AuthenticatedAppWorkflowsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiGenerateContentRoute: ApiGenerateContentRoute,
  ApiGenerateWeeklyPlanRoute: ApiGenerateWeeklyPlanRoute,
  ApiSaveAutomationRoute: ApiSaveAutomationRoute,
  ApiWorkflowRoute: ApiWorkflowRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
  ApiPublicBillingPortalRoute: ApiPublicBillingPortalRoute,
  ApiPublicChatbotBusiness_idRoute: ApiPublicChatbotBusiness_idRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
