/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RequestRouteImport } from './routes/request'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConsumerAuthenticatedRouteRouteImport } from './routes/_consumerAuthenticated/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RequestAuthRouteImport } from './routes/request.auth'
import { Route as CheckoutStartRouteImport } from './routes/checkout.start'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as ApiWorkflowRouteImport } from './routes/api/workflow'
import { Route as ApiTwilioSettingsRouteImport } from './routes/api/twilio-settings'
import { Route as ApiSaveAutomationRouteImport } from './routes/api/save-automation'
import { Route as ApiReviewResponseRouteImport } from './routes/api/review-response'
import { Route as ApiReviewRequestRouteImport } from './routes/api/review-request'
import { Route as ApiReceptionistPreviewRouteImport } from './routes/api/receptionist-preview'
import { Route as ApiConsumerRequestsRouteImport } from './routes/api/consumer-requests'
import { Route as ApiCompetitorIntelRouteImport } from './routes/api/competitor-intel'
import { Route as ApiBookingPlanRouteImport } from './routes/api/booking-plan'
import { Route as ApiAppointmentsRouteImport } from './routes/api/appointments'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiTwilioSmsReplyRouteImport } from './routes/api/twilio/sms-reply'
import { Route as ApiTwilioMissedCallRouteImport } from './routes/api/twilio/missed-call'
import { Route as ApiTwilioConsumerInboundRouteImport } from './routes/api/twilio/consumer-inbound'
import { Route as ApiReviewRequestsIdRouteImport } from './routes/api/review-requests/$id'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiLeadGeneratorResearchRouteImport } from './routes/api/lead-generator/research'
import { Route as ApiLeadGeneratorHandleResponseRouteImport } from './routes/api/lead-generator/handle-response'
import { Route as ApiLeadGeneratorExecuteStepRouteImport } from './routes/api/lead-generator/execute-step'
import { Route as ApiInboxSendRouteImport } from './routes/api/inbox/send'
import { Route as ApiCronQuoteFollowUpsRouteImport } from './routes/api/cron/quote-follow-ups'
import { Route as ApiCronDailyBriefRouteImport } from './routes/api/cron/daily-brief'
import { Route as ApiConsumerRequestsMatchIdRouteImport } from './routes/api/consumer-requests/$matchId'
import { Route as ApiCoachBriefRouteImport } from './routes/api/coach/brief'
import { Route as ApiBusinessFactsSyncWebsiteRouteImport } from './routes/api/business-facts/sync-website'
import { Route as ApiBusinessFactsSyncGoogleRouteImport } from './routes/api/business-facts/sync-google'
import { Route as ApiBusinessFactsSearchGooglePlacesRouteImport } from './routes/api/business-facts/search-google-places'
import { Route as ApiAppointmentsIdRouteImport } from './routes/api/appointments/$id'
import { Route as ApiAdminVerificationReviewRouteImport } from './routes/api/admin/verification-review'
import { Route as ApiAdminUpdateScoresRouteImport } from './routes/api/admin/update-scores'
import { Route as ApiAdminUpdatePricingIndexRouteImport } from './routes/api/admin/update-pricing-index'
import { Route as ApiAccountExportRouteImport } from './routes/api/account/export'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as ConsumerAuthenticatedRequestNewRouteImport } from './routes/_consumerAuthenticated/request.new'
import { Route as AuthenticatedAppWebChatRouteImport } from './routes/_authenticated/app.web-chat'
import { Route as AuthenticatedAppVerificationRouteImport } from './routes/_authenticated/app.verification'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppReputationRouteImport } from './routes/_authenticated/app.reputation'
import { Route as AuthenticatedAppReceptionistRouteImport } from './routes/_authenticated/app.receptionist'
import { Route as AuthenticatedAppNetworkRouteImport } from './routes/_authenticated/app.network'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppInboxRouteImport } from './routes/_authenticated/app.inbox'
import { Route as AuthenticatedAppCoachRouteImport } from './routes/_authenticated/app.coach'
import { Route as AuthenticatedAppCalendarRouteImport } from './routes/_authenticated/app.calendar'
import { Route as AuthenticatedAppBusinessFactsRouteImport } from './routes/_authenticated/app.business-facts'
import { Route as AuthenticatedAppBillingRouteImport } from './routes/_authenticated/app.billing'
import { Route as AuthenticatedAppAgentsRouteImport } from './routes/_authenticated/app.agents'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as ApiPublicWebChatBusiness_idRouteImport } from './routes/api/public/web-chat/$business_id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAppAdminVerificationReviewRouteImport } from './routes/_authenticated/app.admin.verification-review'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerAuthenticatedRouteRoute =
  ConsumerAuthenticatedRouteRouteImport.update({
    id: '/_consumerAuthenticated',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestAuthRoute = RequestAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => RequestRoute,
} as any)
const CheckoutStartRoute = CheckoutStartRouteImport.update({
  id: '/checkout/start',
  path: '/checkout/start',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiWorkflowRoute = ApiWorkflowRouteImport.update({
  id: '/api/workflow',
  path: '/api/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioSettingsRoute = ApiTwilioSettingsRouteImport.update({
  id: '/api/twilio-settings',
  path: '/api/twilio-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaveAutomationRoute = ApiSaveAutomationRouteImport.update({
  id: '/api/save-automation',
  path: '/api/save-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewResponseRoute = ApiReviewResponseRouteImport.update({
  id: '/api/review-response',
  path: '/api/review-response',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRequestRoute = ApiReviewRequestRouteImport.update({
  id: '/api/review-request',
  path: '/api/review-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReceptionistPreviewRoute = ApiReceptionistPreviewRouteImport.update({
  id: '/api/receptionist-preview',
  path: '/api/receptionist-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsumerRequestsRoute = ApiConsumerRequestsRouteImport.update({
  id: '/api/consumer-requests',
  path: '/api/consumer-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompetitorIntelRoute = ApiCompetitorIntelRouteImport.update({
  id: '/api/competitor-intel',
  path: '/api/competitor-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingPlanRoute = ApiBookingPlanRouteImport.update({
  id: '/api/booking-plan',
  path: '/api/booking-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppointmentsRoute = ApiAppointmentsRouteImport.update({
  id: '/api/appointments',
  path: '/api/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiTwilioSmsReplyRoute = ApiTwilioSmsReplyRouteImport.update({
  id: '/api/twilio/sms-reply',
  path: '/api/twilio/sms-reply',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioMissedCallRoute = ApiTwilioMissedCallRouteImport.update({
  id: '/api/twilio/missed-call',
  path: '/api/twilio/missed-call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwilioConsumerInboundRoute =
  ApiTwilioConsumerInboundRouteImport.update({
    id: '/api/twilio/consumer-inbound',
    path: '/api/twilio/consumer-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiReviewRequestsIdRoute = ApiReviewRequestsIdRouteImport.update({
  id: '/api/review-requests/$id',
  path: '/api/review-requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadGeneratorResearchRoute =
  ApiLeadGeneratorResearchRouteImport.update({
    id: '/api/lead-generator/research',
    path: '/api/lead-generator/research',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLeadGeneratorHandleResponseRoute =
  ApiLeadGeneratorHandleResponseRouteImport.update({
    id: '/api/lead-generator/handle-response',
    path: '/api/lead-generator/handle-response',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiLeadGeneratorExecuteStepRoute =
  ApiLeadGeneratorExecuteStepRouteImport.update({
    id: '/api/lead-generator/execute-step',
    path: '/api/lead-generator/execute-step',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInboxSendRoute = ApiInboxSendRouteImport.update({
  id: '/api/inbox/send',
  path: '/api/inbox/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronQuoteFollowUpsRoute = ApiCronQuoteFollowUpsRouteImport.update({
  id: '/api/cron/quote-follow-ups',
  path: '/api/cron/quote-follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronDailyBriefRoute = ApiCronDailyBriefRouteImport.update({
  id: '/api/cron/daily-brief',
  path: '/api/cron/daily-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsumerRequestsMatchIdRoute =
  ApiConsumerRequestsMatchIdRouteImport.update({
    id: '/$matchId',
    path: '/$matchId',
    getParentRoute: () => ApiConsumerRequestsRoute,
  } as any)
const ApiCoachBriefRoute = ApiCoachBriefRouteImport.update({
  id: '/api/coach/brief',
  path: '/api/coach/brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBusinessFactsSyncWebsiteRoute =
  ApiBusinessFactsSyncWebsiteRouteImport.update({
    id: '/api/business-facts/sync-website',
    path: '/api/business-facts/sync-website',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBusinessFactsSyncGoogleRoute =
  ApiBusinessFactsSyncGoogleRouteImport.update({
    id: '/api/business-facts/sync-google',
    path: '/api/business-facts/sync-google',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBusinessFactsSearchGooglePlacesRoute =
  ApiBusinessFactsSearchGooglePlacesRouteImport.update({
    id: '/api/business-facts/search-google-places',
    path: '/api/business-facts/search-google-places',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAppointmentsIdRoute = ApiAppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAppointmentsRoute,
} as any)
const ApiAdminVerificationReviewRoute =
  ApiAdminVerificationReviewRouteImport.update({
    id: '/api/admin/verification-review',
    path: '/api/admin/verification-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUpdateScoresRoute = ApiAdminUpdateScoresRouteImport.update({
  id: '/api/admin/update-scores',
  path: '/api/admin/update-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUpdatePricingIndexRoute =
  ApiAdminUpdatePricingIndexRouteImport.update({
    id: '/api/admin/update-pricing-index',
    path: '/api/admin/update-pricing-index',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAccountExportRoute = ApiAccountExportRouteImport.update({
  id: '/api/account/export',
  path: '/api/account/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumerAuthenticatedRequestNewRoute =
  ConsumerAuthenticatedRequestNewRouteImport.update({
    id: '/request/new',
    path: '/request/new',
    getParentRoute: () => ConsumerAuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppWebChatRoute = AuthenticatedAppWebChatRouteImport.update({
  id: '/web-chat',
  path: '/web-chat',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppVerificationRoute =
  AuthenticatedAppVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReputationRoute =
  AuthenticatedAppReputationRouteImport.update({
    id: '/reputation',
    path: '/reputation',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReceptionistRoute =
  AuthenticatedAppReceptionistRouteImport.update({
    id: '/receptionist',
    path: '/receptionist',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNetworkRoute = AuthenticatedAppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInboxRoute = AuthenticatedAppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCoachRoute = AuthenticatedAppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCalendarRoute =
  AuthenticatedAppCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBusinessFactsRoute =
  AuthenticatedAppBusinessFactsRouteImport.update({
    id: '/business-facts',
    path: '/business-facts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBillingRoute = AuthenticatedAppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgentsRoute = AuthenticatedAppAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicWebChatBusiness_idRoute =
  ApiPublicWebChatBusiness_idRouteImport.update({
    id: '/api/public/web-chat/$business_id',
    path: '/api/public/web-chat/$business_id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppAdminVerificationReviewRoute =
  AuthenticatedAppAdminVerificationReviewRouteImport.update({
    id: '/verification-review',
    path: '/verification-review',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/request': typeof RequestRouteWithChildren
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/appointments': typeof ApiAppointmentsRouteWithChildren
  '/api/booking-plan': typeof ApiBookingPlanRoute
  '/api/competitor-intel': typeof ApiCompetitorIntelRoute
  '/api/consumer-requests': typeof ApiConsumerRequestsRouteWithChildren
  '/api/receptionist-preview': typeof ApiReceptionistPreviewRoute
  '/api/review-request': typeof ApiReviewRequestRoute
  '/api/review-response': typeof ApiReviewResponseRoute
  '/api/save-automation': typeof ApiSaveAutomationRoute
  '/api/twilio-settings': typeof ApiTwilioSettingsRoute
  '/api/workflow': typeof ApiWorkflowRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/start': typeof CheckoutStartRoute
  '/request/auth': typeof RequestAuthRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/agents': typeof AuthenticatedAppAgentsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/business-facts': typeof AuthenticatedAppBusinessFactsRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/coach': typeof AuthenticatedAppCoachRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/network': typeof AuthenticatedAppNetworkRoute
  '/app/receptionist': typeof AuthenticatedAppReceptionistRoute
  '/app/reputation': typeof AuthenticatedAppReputationRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/verification': typeof AuthenticatedAppVerificationRoute
  '/app/web-chat': typeof AuthenticatedAppWebChatRoute
  '/request/new': typeof ConsumerAuthenticatedRequestNewRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/admin/update-pricing-index': typeof ApiAdminUpdatePricingIndexRoute
  '/api/admin/update-scores': typeof ApiAdminUpdateScoresRoute
  '/api/admin/verification-review': typeof ApiAdminVerificationReviewRoute
  '/api/appointments/$id': typeof ApiAppointmentsIdRoute
  '/api/business-facts/search-google-places': typeof ApiBusinessFactsSearchGooglePlacesRoute
  '/api/business-facts/sync-google': typeof ApiBusinessFactsSyncGoogleRoute
  '/api/business-facts/sync-website': typeof ApiBusinessFactsSyncWebsiteRoute
  '/api/coach/brief': typeof ApiCoachBriefRoute
  '/api/consumer-requests/$matchId': typeof ApiConsumerRequestsMatchIdRoute
  '/api/cron/daily-brief': typeof ApiCronDailyBriefRoute
  '/api/cron/quote-follow-ups': typeof ApiCronQuoteFollowUpsRoute
  '/api/inbox/send': typeof ApiInboxSendRoute
  '/api/lead-generator/execute-step': typeof ApiLeadGeneratorExecuteStepRoute
  '/api/lead-generator/handle-response': typeof ApiLeadGeneratorHandleResponseRoute
  '/api/lead-generator/research': typeof ApiLeadGeneratorResearchRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/review-requests/$id': typeof ApiReviewRequestsIdRoute
  '/api/twilio/consumer-inbound': typeof ApiTwilioConsumerInboundRoute
  '/api/twilio/missed-call': typeof ApiTwilioMissedCallRoute
  '/api/twilio/sms-reply': typeof ApiTwilioSmsReplyRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/verification-review': typeof AuthenticatedAppAdminVerificationReviewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/web-chat/$business_id': typeof ApiPublicWebChatBusiness_idRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/request': typeof RequestRouteWithChildren
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/appointments': typeof ApiAppointmentsRouteWithChildren
  '/api/booking-plan': typeof ApiBookingPlanRoute
  '/api/competitor-intel': typeof ApiCompetitorIntelRoute
  '/api/consumer-requests': typeof ApiConsumerRequestsRouteWithChildren
  '/api/receptionist-preview': typeof ApiReceptionistPreviewRoute
  '/api/review-request': typeof ApiReviewRequestRoute
  '/api/review-response': typeof ApiReviewResponseRoute
  '/api/save-automation': typeof ApiSaveAutomationRoute
  '/api/twilio-settings': typeof ApiTwilioSettingsRoute
  '/api/workflow': typeof ApiWorkflowRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/start': typeof CheckoutStartRoute
  '/request/auth': typeof RequestAuthRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/agents': typeof AuthenticatedAppAgentsRoute
  '/app/billing': typeof AuthenticatedAppBillingRoute
  '/app/business-facts': typeof AuthenticatedAppBusinessFactsRoute
  '/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/app/coach': typeof AuthenticatedAppCoachRoute
  '/app/inbox': typeof AuthenticatedAppInboxRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/network': typeof AuthenticatedAppNetworkRoute
  '/app/receptionist': typeof AuthenticatedAppReceptionistRoute
  '/app/reputation': typeof AuthenticatedAppReputationRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/verification': typeof AuthenticatedAppVerificationRoute
  '/app/web-chat': typeof AuthenticatedAppWebChatRoute
  '/request/new': typeof ConsumerAuthenticatedRequestNewRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/admin/update-pricing-index': typeof ApiAdminUpdatePricingIndexRoute
  '/api/admin/update-scores': typeof ApiAdminUpdateScoresRoute
  '/api/admin/verification-review': typeof ApiAdminVerificationReviewRoute
  '/api/appointments/$id': typeof ApiAppointmentsIdRoute
  '/api/business-facts/search-google-places': typeof ApiBusinessFactsSearchGooglePlacesRoute
  '/api/business-facts/sync-google': typeof ApiBusinessFactsSyncGoogleRoute
  '/api/business-facts/sync-website': typeof ApiBusinessFactsSyncWebsiteRoute
  '/api/coach/brief': typeof ApiCoachBriefRoute
  '/api/consumer-requests/$matchId': typeof ApiConsumerRequestsMatchIdRoute
  '/api/cron/daily-brief': typeof ApiCronDailyBriefRoute
  '/api/cron/quote-follow-ups': typeof ApiCronQuoteFollowUpsRoute
  '/api/inbox/send': typeof ApiInboxSendRoute
  '/api/lead-generator/execute-step': typeof ApiLeadGeneratorExecuteStepRoute
  '/api/lead-generator/handle-response': typeof ApiLeadGeneratorHandleResponseRoute
  '/api/lead-generator/research': typeof ApiLeadGeneratorResearchRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/review-requests/$id': typeof ApiReviewRequestsIdRoute
  '/api/twilio/consumer-inbound': typeof ApiTwilioConsumerInboundRoute
  '/api/twilio/missed-call': typeof ApiTwilioMissedCallRoute
  '/api/twilio/sms-reply': typeof ApiTwilioSmsReplyRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/verification-review': typeof AuthenticatedAppAdminVerificationReviewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/web-chat/$business_id': typeof ApiPublicWebChatBusiness_idRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_consumerAuthenticated': typeof ConsumerAuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRouteWithChildren
  '/chat': typeof ChatRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/request': typeof RequestRouteWithChildren
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/appointments': typeof ApiAppointmentsRouteWithChildren
  '/api/booking-plan': typeof ApiBookingPlanRoute
  '/api/competitor-intel': typeof ApiCompetitorIntelRoute
  '/api/consumer-requests': typeof ApiConsumerRequestsRouteWithChildren
  '/api/receptionist-preview': typeof ApiReceptionistPreviewRoute
  '/api/review-request': typeof ApiReviewRequestRoute
  '/api/review-response': typeof ApiReviewResponseRoute
  '/api/save-automation': typeof ApiSaveAutomationRoute
  '/api/twilio-settings': typeof ApiTwilioSettingsRoute
  '/api/workflow': typeof ApiWorkflowRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/checkout/start': typeof CheckoutStartRoute
  '/request/auth': typeof RequestAuthRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/agents': typeof AuthenticatedAppAgentsRoute
  '/_authenticated/app/billing': typeof AuthenticatedAppBillingRoute
  '/_authenticated/app/business-facts': typeof AuthenticatedAppBusinessFactsRoute
  '/_authenticated/app/calendar': typeof AuthenticatedAppCalendarRoute
  '/_authenticated/app/coach': typeof AuthenticatedAppCoachRoute
  '/_authenticated/app/inbox': typeof AuthenticatedAppInboxRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRoute
  '/_authenticated/app/network': typeof AuthenticatedAppNetworkRoute
  '/_authenticated/app/receptionist': typeof AuthenticatedAppReceptionistRoute
  '/_authenticated/app/reputation': typeof AuthenticatedAppReputationRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/verification': typeof AuthenticatedAppVerificationRoute
  '/_authenticated/app/web-chat': typeof AuthenticatedAppWebChatRoute
  '/_consumerAuthenticated/request/new': typeof ConsumerAuthenticatedRequestNewRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/admin/update-pricing-index': typeof ApiAdminUpdatePricingIndexRoute
  '/api/admin/update-scores': typeof ApiAdminUpdateScoresRoute
  '/api/admin/verification-review': typeof ApiAdminVerificationReviewRoute
  '/api/appointments/$id': typeof ApiAppointmentsIdRoute
  '/api/business-facts/search-google-places': typeof ApiBusinessFactsSearchGooglePlacesRoute
  '/api/business-facts/sync-google': typeof ApiBusinessFactsSyncGoogleRoute
  '/api/business-facts/sync-website': typeof ApiBusinessFactsSyncWebsiteRoute
  '/api/coach/brief': typeof ApiCoachBriefRoute
  '/api/consumer-requests/$matchId': typeof ApiConsumerRequestsMatchIdRoute
  '/api/cron/daily-brief': typeof ApiCronDailyBriefRoute
  '/api/cron/quote-follow-ups': typeof ApiCronQuoteFollowUpsRoute
  '/api/inbox/send': typeof ApiInboxSendRoute
  '/api/lead-generator/execute-step': typeof ApiLeadGeneratorExecuteStepRoute
  '/api/lead-generator/handle-response': typeof ApiLeadGeneratorHandleResponseRoute
  '/api/lead-generator/research': typeof ApiLeadGeneratorResearchRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/review-requests/$id': typeof ApiReviewRequestsIdRoute
  '/api/twilio/consumer-inbound': typeof ApiTwilioConsumerInboundRoute
  '/api/twilio/missed-call': typeof ApiTwilioMissedCallRoute
  '/api/twilio/sms-reply': typeof ApiTwilioSmsReplyRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/verification-review': typeof AuthenticatedAppAdminVerificationReviewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/web-chat/$business_id': typeof ApiPublicWebChatBusiness_idRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/audit'
    | '/auth'
    | '/chat'
    | '/cookies'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/request'
    | '/signup'
    | '/terms'
    | '/app'
    | '/onboarding'
    | '/api/appointments'
    | '/api/booking-plan'
    | '/api/competitor-intel'
    | '/api/consumer-requests'
    | '/api/receptionist-preview'
    | '/api/review-request'
    | '/api/review-response'
    | '/api/save-automation'
    | '/api/twilio-settings'
    | '/api/workflow'
    | '/auth/reset-password'
    | '/checkout/return'
    | '/checkout/start'
    | '/request/auth'
    | '/app/admin'
    | '/app/agents'
    | '/app/billing'
    | '/app/business-facts'
    | '/app/calendar'
    | '/app/coach'
    | '/app/inbox'
    | '/app/leads'
    | '/app/network'
    | '/app/receptionist'
    | '/app/reputation'
    | '/app/settings'
    | '/app/verification'
    | '/app/web-chat'
    | '/request/new'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/admin/update-pricing-index'
    | '/api/admin/update-scores'
    | '/api/admin/verification-review'
    | '/api/appointments/$id'
    | '/api/business-facts/search-google-places'
    | '/api/business-facts/sync-google'
    | '/api/business-facts/sync-website'
    | '/api/coach/brief'
    | '/api/consumer-requests/$matchId'
    | '/api/cron/daily-brief'
    | '/api/cron/quote-follow-ups'
    | '/api/inbox/send'
    | '/api/lead-generator/execute-step'
    | '/api/lead-generator/handle-response'
    | '/api/lead-generator/research'
    | '/api/public/contact'
    | '/api/review-requests/$id'
    | '/api/twilio/consumer-inbound'
    | '/api/twilio/missed-call'
    | '/api/twilio/sms-reply'
    | '/app/'
    | '/app/admin/verification-review'
    | '/api/public/payments/webhook'
    | '/api/public/web-chat/$business_id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/audit'
    | '/auth'
    | '/chat'
    | '/cookies'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/request'
    | '/signup'
    | '/terms'
    | '/onboarding'
    | '/api/appointments'
    | '/api/booking-plan'
    | '/api/competitor-intel'
    | '/api/consumer-requests'
    | '/api/receptionist-preview'
    | '/api/review-request'
    | '/api/review-response'
    | '/api/save-automation'
    | '/api/twilio-settings'
    | '/api/workflow'
    | '/auth/reset-password'
    | '/checkout/return'
    | '/checkout/start'
    | '/request/auth'
    | '/app/admin'
    | '/app/agents'
    | '/app/billing'
    | '/app/business-facts'
    | '/app/calendar'
    | '/app/coach'
    | '/app/inbox'
    | '/app/leads'
    | '/app/network'
    | '/app/receptionist'
    | '/app/reputation'
    | '/app/settings'
    | '/app/verification'
    | '/app/web-chat'
    | '/request/new'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/admin/update-pricing-index'
    | '/api/admin/update-scores'
    | '/api/admin/verification-review'
    | '/api/appointments/$id'
    | '/api/business-facts/search-google-places'
    | '/api/business-facts/sync-google'
    | '/api/business-facts/sync-website'
    | '/api/coach/brief'
    | '/api/consumer-requests/$matchId'
    | '/api/cron/daily-brief'
    | '/api/cron/quote-follow-ups'
    | '/api/inbox/send'
    | '/api/lead-generator/execute-step'
    | '/api/lead-generator/handle-response'
    | '/api/lead-generator/research'
    | '/api/public/contact'
    | '/api/review-requests/$id'
    | '/api/twilio/consumer-inbound'
    | '/api/twilio/missed-call'
    | '/api/twilio/sms-reply'
    | '/app'
    | '/app/admin/verification-review'
    | '/api/public/payments/webhook'
    | '/api/public/web-chat/$business_id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_consumerAuthenticated'
    | '/about'
    | '/audit'
    | '/auth'
    | '/chat'
    | '/cookies'
    | '/dashboard'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/request'
    | '/signup'
    | '/terms'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/api/appointments'
    | '/api/booking-plan'
    | '/api/competitor-intel'
    | '/api/consumer-requests'
    | '/api/receptionist-preview'
    | '/api/review-request'
    | '/api/review-response'
    | '/api/save-automation'
    | '/api/twilio-settings'
    | '/api/workflow'
    | '/auth/reset-password'
    | '/checkout/return'
    | '/checkout/start'
    | '/request/auth'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/agents'
    | '/_authenticated/app/billing'
    | '/_authenticated/app/business-facts'
    | '/_authenticated/app/calendar'
    | '/_authenticated/app/coach'
    | '/_authenticated/app/inbox'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/network'
    | '/_authenticated/app/receptionist'
    | '/_authenticated/app/reputation'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/verification'
    | '/_authenticated/app/web-chat'
    | '/_consumerAuthenticated/request/new'
    | '/api/account/delete'
    | '/api/account/export'
    | '/api/admin/update-pricing-index'
    | '/api/admin/update-scores'
    | '/api/admin/verification-review'
    | '/api/appointments/$id'
    | '/api/business-facts/search-google-places'
    | '/api/business-facts/sync-google'
    | '/api/business-facts/sync-website'
    | '/api/coach/brief'
    | '/api/consumer-requests/$matchId'
    | '/api/cron/daily-brief'
    | '/api/cron/quote-follow-ups'
    | '/api/inbox/send'
    | '/api/lead-generator/execute-step'
    | '/api/lead-generator/handle-response'
    | '/api/lead-generator/research'
    | '/api/public/contact'
    | '/api/review-requests/$id'
    | '/api/twilio/consumer-inbound'
    | '/api/twilio/missed-call'
    | '/api/twilio/sms-reply'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/verification-review'
    | '/api/public/payments/webhook'
    | '/api/public/web-chat/$business_id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ConsumerAuthenticatedRouteRoute: typeof ConsumerAuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRouteWithChildren
  ChatRoute: typeof ChatRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RequestRoute: typeof RequestRouteWithChildren
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiAppointmentsRoute: typeof ApiAppointmentsRouteWithChildren
  ApiBookingPlanRoute: typeof ApiBookingPlanRoute
  ApiCompetitorIntelRoute: typeof ApiCompetitorIntelRoute
  ApiConsumerRequestsRoute: typeof ApiConsumerRequestsRouteWithChildren
  ApiReceptionistPreviewRoute: typeof ApiReceptionistPreviewRoute
  ApiReviewRequestRoute: typeof ApiReviewRequestRoute
  ApiReviewResponseRoute: typeof ApiReviewResponseRoute
  ApiSaveAutomationRoute: typeof ApiSaveAutomationRoute
  ApiTwilioSettingsRoute: typeof ApiTwilioSettingsRoute
  ApiWorkflowRoute: typeof ApiWorkflowRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  CheckoutStartRoute: typeof CheckoutStartRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAccountExportRoute: typeof ApiAccountExportRoute
  ApiAdminUpdatePricingIndexRoute: typeof ApiAdminUpdatePricingIndexRoute
  ApiAdminUpdateScoresRoute: typeof ApiAdminUpdateScoresRoute
  ApiAdminVerificationReviewRoute: typeof ApiAdminVerificationReviewRoute
  ApiBusinessFactsSearchGooglePlacesRoute: typeof ApiBusinessFactsSearchGooglePlacesRoute
  ApiBusinessFactsSyncGoogleRoute: typeof ApiBusinessFactsSyncGoogleRoute
  ApiBusinessFactsSyncWebsiteRoute: typeof ApiBusinessFactsSyncWebsiteRoute
  ApiCoachBriefRoute: typeof ApiCoachBriefRoute
  ApiCronDailyBriefRoute: typeof ApiCronDailyBriefRoute
  ApiCronQuoteFollowUpsRoute: typeof ApiCronQuoteFollowUpsRoute
  ApiInboxSendRoute: typeof ApiInboxSendRoute
  ApiLeadGeneratorExecuteStepRoute: typeof ApiLeadGeneratorExecuteStepRoute
  ApiLeadGeneratorHandleResponseRoute: typeof ApiLeadGeneratorHandleResponseRoute
  ApiLeadGeneratorResearchRoute: typeof ApiLeadGeneratorResearchRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiReviewRequestsIdRoute: typeof ApiReviewRequestsIdRoute
  ApiTwilioConsumerInboundRoute: typeof ApiTwilioConsumerInboundRoute
  ApiTwilioMissedCallRoute: typeof ApiTwilioMissedCallRoute
  ApiTwilioSmsReplyRoute: typeof ApiTwilioSmsReplyRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWebChatBusiness_idRoute: typeof ApiPublicWebChatBusiness_idRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_consumerAuthenticated': {
      id: '/_consumerAuthenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ConsumerAuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/auth': {
      id: '/request/auth'
      path: '/auth'
      fullPath: '/request/auth'
      preLoaderRoute: typeof RequestAuthRouteImport
      parentRoute: typeof RequestRoute
    }
    '/checkout/start': {
      id: '/checkout/start'
      path: '/checkout/start'
      fullPath: '/checkout/start'
      preLoaderRoute: typeof CheckoutStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/workflow': {
      id: '/api/workflow'
      path: '/api/workflow'
      fullPath: '/api/workflow'
      preLoaderRoute: typeof ApiWorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio-settings': {
      id: '/api/twilio-settings'
      path: '/api/twilio-settings'
      fullPath: '/api/twilio-settings'
      preLoaderRoute: typeof ApiTwilioSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-automation': {
      id: '/api/save-automation'
      path: '/api/save-automation'
      fullPath: '/api/save-automation'
      preLoaderRoute: typeof ApiSaveAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-response': {
      id: '/api/review-response'
      path: '/api/review-response'
      fullPath: '/api/review-response'
      preLoaderRoute: typeof ApiReviewResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-request': {
      id: '/api/review-request'
      path: '/api/review-request'
      fullPath: '/api/review-request'
      preLoaderRoute: typeof ApiReviewRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/receptionist-preview': {
      id: '/api/receptionist-preview'
      path: '/api/receptionist-preview'
      fullPath: '/api/receptionist-preview'
      preLoaderRoute: typeof ApiReceptionistPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consumer-requests': {
      id: '/api/consumer-requests'
      path: '/api/consumer-requests'
      fullPath: '/api/consumer-requests'
      preLoaderRoute: typeof ApiConsumerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/competitor-intel': {
      id: '/api/competitor-intel'
      path: '/api/competitor-intel'
      fullPath: '/api/competitor-intel'
      preLoaderRoute: typeof ApiCompetitorIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-plan': {
      id: '/api/booking-plan'
      path: '/api/booking-plan'
      fullPath: '/api/booking-plan'
      preLoaderRoute: typeof ApiBookingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appointments': {
      id: '/api/appointments'
      path: '/api/appointments'
      fullPath: '/api/appointments'
      preLoaderRoute: typeof ApiAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/twilio/sms-reply': {
      id: '/api/twilio/sms-reply'
      path: '/api/twilio/sms-reply'
      fullPath: '/api/twilio/sms-reply'
      preLoaderRoute: typeof ApiTwilioSmsReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/missed-call': {
      id: '/api/twilio/missed-call'
      path: '/api/twilio/missed-call'
      fullPath: '/api/twilio/missed-call'
      preLoaderRoute: typeof ApiTwilioMissedCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twilio/consumer-inbound': {
      id: '/api/twilio/consumer-inbound'
      path: '/api/twilio/consumer-inbound'
      fullPath: '/api/twilio/consumer-inbound'
      preLoaderRoute: typeof ApiTwilioConsumerInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review-requests/$id': {
      id: '/api/review-requests/$id'
      path: '/api/review-requests/$id'
      fullPath: '/api/review-requests/$id'
      preLoaderRoute: typeof ApiReviewRequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-generator/research': {
      id: '/api/lead-generator/research'
      path: '/api/lead-generator/research'
      fullPath: '/api/lead-generator/research'
      preLoaderRoute: typeof ApiLeadGeneratorResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-generator/handle-response': {
      id: '/api/lead-generator/handle-response'
      path: '/api/lead-generator/handle-response'
      fullPath: '/api/lead-generator/handle-response'
      preLoaderRoute: typeof ApiLeadGeneratorHandleResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-generator/execute-step': {
      id: '/api/lead-generator/execute-step'
      path: '/api/lead-generator/execute-step'
      fullPath: '/api/lead-generator/execute-step'
      preLoaderRoute: typeof ApiLeadGeneratorExecuteStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inbox/send': {
      id: '/api/inbox/send'
      path: '/api/inbox/send'
      fullPath: '/api/inbox/send'
      preLoaderRoute: typeof ApiInboxSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/quote-follow-ups': {
      id: '/api/cron/quote-follow-ups'
      path: '/api/cron/quote-follow-ups'
      fullPath: '/api/cron/quote-follow-ups'
      preLoaderRoute: typeof ApiCronQuoteFollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/daily-brief': {
      id: '/api/cron/daily-brief'
      path: '/api/cron/daily-brief'
      fullPath: '/api/cron/daily-brief'
      preLoaderRoute: typeof ApiCronDailyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consumer-requests/$matchId': {
      id: '/api/consumer-requests/$matchId'
      path: '/$matchId'
      fullPath: '/api/consumer-requests/$matchId'
      preLoaderRoute: typeof ApiConsumerRequestsMatchIdRouteImport
      parentRoute: typeof ApiConsumerRequestsRoute
    }
    '/api/coach/brief': {
      id: '/api/coach/brief'
      path: '/api/coach/brief'
      fullPath: '/api/coach/brief'
      preLoaderRoute: typeof ApiCoachBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/business-facts/sync-website': {
      id: '/api/business-facts/sync-website'
      path: '/api/business-facts/sync-website'
      fullPath: '/api/business-facts/sync-website'
      preLoaderRoute: typeof ApiBusinessFactsSyncWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/business-facts/sync-google': {
      id: '/api/business-facts/sync-google'
      path: '/api/business-facts/sync-google'
      fullPath: '/api/business-facts/sync-google'
      preLoaderRoute: typeof ApiBusinessFactsSyncGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/business-facts/search-google-places': {
      id: '/api/business-facts/search-google-places'
      path: '/api/business-facts/search-google-places'
      fullPath: '/api/business-facts/search-google-places'
      preLoaderRoute: typeof ApiBusinessFactsSearchGooglePlacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/appointments/$id': {
      id: '/api/appointments/$id'
      path: '/$id'
      fullPath: '/api/appointments/$id'
      preLoaderRoute: typeof ApiAppointmentsIdRouteImport
      parentRoute: typeof ApiAppointmentsRoute
    }
    '/api/admin/verification-review': {
      id: '/api/admin/verification-review'
      path: '/api/admin/verification-review'
      fullPath: '/api/admin/verification-review'
      preLoaderRoute: typeof ApiAdminVerificationReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-scores': {
      id: '/api/admin/update-scores'
      path: '/api/admin/update-scores'
      fullPath: '/api/admin/update-scores'
      preLoaderRoute: typeof ApiAdminUpdateScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/update-pricing-index': {
      id: '/api/admin/update-pricing-index'
      path: '/api/admin/update-pricing-index'
      fullPath: '/api/admin/update-pricing-index'
      preLoaderRoute: typeof ApiAdminUpdatePricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/export': {
      id: '/api/account/export'
      path: '/api/account/export'
      fullPath: '/api/account/export'
      preLoaderRoute: typeof ApiAccountExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_consumerAuthenticated/request/new': {
      id: '/_consumerAuthenticated/request/new'
      path: '/request/new'
      fullPath: '/request/new'
      preLoaderRoute: typeof ConsumerAuthenticatedRequestNewRouteImport
      parentRoute: typeof ConsumerAuthenticatedRouteRoute
    }
    '/_authenticated/app/web-chat': {
      id: '/_authenticated/app/web-chat'
      path: '/web-chat'
      fullPath: '/app/web-chat'
      preLoaderRoute: typeof AuthenticatedAppWebChatRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/verification': {
      id: '/_authenticated/app/verification'
      path: '/verification'
      fullPath: '/app/verification'
      preLoaderRoute: typeof AuthenticatedAppVerificationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reputation': {
      id: '/_authenticated/app/reputation'
      path: '/reputation'
      fullPath: '/app/reputation'
      preLoaderRoute: typeof AuthenticatedAppReputationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/receptionist': {
      id: '/_authenticated/app/receptionist'
      path: '/receptionist'
      fullPath: '/app/receptionist'
      preLoaderRoute: typeof AuthenticatedAppReceptionistRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/network': {
      id: '/_authenticated/app/network'
      path: '/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AuthenticatedAppNetworkRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inbox': {
      id: '/_authenticated/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AuthenticatedAppInboxRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/coach': {
      id: '/_authenticated/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AuthenticatedAppCoachRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/calendar': {
      id: '/_authenticated/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AuthenticatedAppCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/business-facts': {
      id: '/_authenticated/app/business-facts'
      path: '/business-facts'
      fullPath: '/app/business-facts'
      preLoaderRoute: typeof AuthenticatedAppBusinessFactsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/billing': {
      id: '/_authenticated/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AuthenticatedAppBillingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agents': {
      id: '/_authenticated/app/agents'
      path: '/agents'
      fullPath: '/app/agents'
      preLoaderRoute: typeof AuthenticatedAppAgentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/web-chat/$business_id': {
      id: '/api/public/web-chat/$business_id'
      path: '/api/public/web-chat/$business_id'
      fullPath: '/api/public/web-chat/$business_id'
      preLoaderRoute: typeof ApiPublicWebChatBusiness_idRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/admin/verification-review': {
      id: '/_authenticated/app/admin/verification-review'
      path: '/verification-review'
      fullPath: '/app/admin/verification-review'
      preLoaderRoute: typeof AuthenticatedAppAdminVerificationReviewRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminVerificationReviewRoute: typeof AuthenticatedAppAdminVerificationReviewRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminVerificationReviewRoute:
    AuthenticatedAppAdminVerificationReviewRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppAgentsRoute: typeof AuthenticatedAppAgentsRoute
  AuthenticatedAppBillingRoute: typeof AuthenticatedAppBillingRoute
  AuthenticatedAppBusinessFactsRoute: typeof AuthenticatedAppBusinessFactsRoute
  AuthenticatedAppCalendarRoute: typeof AuthenticatedAppCalendarRoute
  AuthenticatedAppCoachRoute: typeof AuthenticatedAppCoachRoute
  AuthenticatedAppInboxRoute: typeof AuthenticatedAppInboxRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRoute
  AuthenticatedAppNetworkRoute: typeof AuthenticatedAppNetworkRoute
  AuthenticatedAppReceptionistRoute: typeof AuthenticatedAppReceptionistRoute
  AuthenticatedAppReputationRoute: typeof AuthenticatedAppReputationRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppVerificationRoute: typeof AuthenticatedAppVerificationRoute
  AuthenticatedAppWebChatRoute: typeof AuthenticatedAppWebChatRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppAgentsRoute: AuthenticatedAppAgentsRoute,
  AuthenticatedAppBillingRoute: AuthenticatedAppBillingRoute,
  AuthenticatedAppBusinessFactsRoute: AuthenticatedAppBusinessFactsRoute,
  AuthenticatedAppCalendarRoute: AuthenticatedAppCalendarRoute,
  AuthenticatedAppCoachRoute: AuthenticatedAppCoachRoute,
  AuthenticatedAppInboxRoute: AuthenticatedAppInboxRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRoute,
  AuthenticatedAppNetworkRoute: AuthenticatedAppNetworkRoute,
  AuthenticatedAppReceptionistRoute: AuthenticatedAppReceptionistRoute,
  AuthenticatedAppReputationRoute: AuthenticatedAppReputationRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppVerificationRoute: AuthenticatedAppVerificationRoute,
  AuthenticatedAppWebChatRoute: AuthenticatedAppWebChatRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ConsumerAuthenticatedRouteRouteChildren {
  ConsumerAuthenticatedRequestNewRoute: typeof ConsumerAuthenticatedRequestNewRoute
}

const ConsumerAuthenticatedRouteRouteChildren: ConsumerAuthenticatedRouteRouteChildren =
  {
    ConsumerAuthenticatedRequestNewRoute: ConsumerAuthenticatedRequestNewRoute,
  }

const ConsumerAuthenticatedRouteRouteWithChildren =
  ConsumerAuthenticatedRouteRoute._addFileChildren(
    ConsumerAuthenticatedRouteRouteChildren,
  )

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface RequestRouteChildren {
  RequestAuthRoute: typeof RequestAuthRoute
}

const RequestRouteChildren: RequestRouteChildren = {
  RequestAuthRoute: RequestAuthRoute,
}

const RequestRouteWithChildren =
  RequestRoute._addFileChildren(RequestRouteChildren)

interface ApiAppointmentsRouteChildren {
  ApiAppointmentsIdRoute: typeof ApiAppointmentsIdRoute
}

const ApiAppointmentsRouteChildren: ApiAppointmentsRouteChildren = {
  ApiAppointmentsIdRoute: ApiAppointmentsIdRoute,
}

const ApiAppointmentsRouteWithChildren = ApiAppointmentsRoute._addFileChildren(
  ApiAppointmentsRouteChildren,
)

interface ApiConsumerRequestsRouteChildren {
  ApiConsumerRequestsMatchIdRoute: typeof ApiConsumerRequestsMatchIdRoute
}

const ApiConsumerRequestsRouteChildren: ApiConsumerRequestsRouteChildren = {
  ApiConsumerRequestsMatchIdRoute: ApiConsumerRequestsMatchIdRoute,
}

const ApiConsumerRequestsRouteWithChildren =
  ApiConsumerRequestsRoute._addFileChildren(ApiConsumerRequestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ConsumerAuthenticatedRouteRoute: ConsumerAuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRouteWithChildren,
  ChatRoute: ChatRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RequestRoute: RequestRouteWithChildren,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiAppointmentsRoute: ApiAppointmentsRouteWithChildren,
  ApiBookingPlanRoute: ApiBookingPlanRoute,
  ApiCompetitorIntelRoute: ApiCompetitorIntelRoute,
  ApiConsumerRequestsRoute: ApiConsumerRequestsRouteWithChildren,
  ApiReceptionistPreviewRoute: ApiReceptionistPreviewRoute,
  ApiReviewRequestRoute: ApiReviewRequestRoute,
  ApiReviewResponseRoute: ApiReviewResponseRoute,
  ApiSaveAutomationRoute: ApiSaveAutomationRoute,
  ApiTwilioSettingsRoute: ApiTwilioSettingsRoute,
  ApiWorkflowRoute: ApiWorkflowRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  CheckoutStartRoute: CheckoutStartRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAccountExportRoute: ApiAccountExportRoute,
  ApiAdminUpdatePricingIndexRoute: ApiAdminUpdatePricingIndexRoute,
  ApiAdminUpdateScoresRoute: ApiAdminUpdateScoresRoute,
  ApiAdminVerificationReviewRoute: ApiAdminVerificationReviewRoute,
  ApiBusinessFactsSearchGooglePlacesRoute:
    ApiBusinessFactsSearchGooglePlacesRoute,
  ApiBusinessFactsSyncGoogleRoute: ApiBusinessFactsSyncGoogleRoute,
  ApiBusinessFactsSyncWebsiteRoute: ApiBusinessFactsSyncWebsiteRoute,
  ApiCoachBriefRoute: ApiCoachBriefRoute,
  ApiCronDailyBriefRoute: ApiCronDailyBriefRoute,
  ApiCronQuoteFollowUpsRoute: ApiCronQuoteFollowUpsRoute,
  ApiInboxSendRoute: ApiInboxSendRoute,
  ApiLeadGeneratorExecuteStepRoute: ApiLeadGeneratorExecuteStepRoute,
  ApiLeadGeneratorHandleResponseRoute: ApiLeadGeneratorHandleResponseRoute,
  ApiLeadGeneratorResearchRoute: ApiLeadGeneratorResearchRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiReviewRequestsIdRoute: ApiReviewRequestsIdRoute,
  ApiTwilioConsumerInboundRoute: ApiTwilioConsumerInboundRoute,
  ApiTwilioMissedCallRoute: ApiTwilioMissedCallRoute,
  ApiTwilioSmsReplyRoute: ApiTwilioSmsReplyRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWebChatBusiness_idRoute: ApiPublicWebChatBusiness_idRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
